sudo: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:git-core/ppa'
    packages:
      - git

language: go

os:
  - linux
  - osx

go:
  - "1.11.x"

before_script:
  - touch "$GOOGLE_APPLICATION_CREDENTIALS" 
  - echo $GOOGLE_CREDENTIALS > "$GOOGLE_APPLICATION_CREDENTIALS"
  - go build ./cmd/go-getter

branches:
  only:
    - master
