version: '3.2'

services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    environment:
      USERID: "0"
      GROUPID: "0"
    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /mnt:/mnt:z # :z allows share to be used by multiple containers
    command: '-s "shared;/data"'

  gogetter:
    image: golang:latest
    container_name: gogetter
    depends_on:
      - samba
    networks:
      - default
    working_dir: /go-getter
    command: tail -f /dev/null
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

networks:
  default: